// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdC3zFfynvJqsYuHY8h93BsDNoBdZAEWc',
    appId: '1:514805253185:android:3522d5b30dc537efb272c0',
    messagingSenderId: '514805253185',
    projectId: 'eventeaze-7c320',
    storageBucket: 'eventeaze-7c320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiN-j7iGG8QrBRfGJrbHFV78vZj0Wadk',
    appId: '1:514805253185:ios:1f77585a5d47930cb272c0',
    messagingSenderId: '514805253185',
    projectId: 'eventeaze-7c320',
    storageBucket: 'eventeaze-7c320.appspot.com',
    androidClientId: '514805253185-3kmlmsrv5ggib8lsjo3rqpdbaokoh58p.apps.googleusercontent.com',
    iosClientId: '514805253185-obforhp7lov20ic8n8mf09uh8rr8p5vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventeaze',
  );
}
